# Generated by Django 5.1.1 on 2025-01-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Appraisal', '0003_facultyprofile_created_at_facultyreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
